os: linux
dist: xenial
language: python
python:
  - "3.6"
sudo: true
install:
  - sudo apt-get -qq update
  - sudo apt-get -y install tesseract-ocr tesseract-ocr-chi-sim libtesseract-dev libleptonica-dev pkg-config
  - sudo apt-get -y install libglib2.0 libsm6 libxrender1 libxext-dev
  - sudo pip install --upgrade Cython
  - sudo pip install --upgrade stagesep2
script: git clone https://github.com/williamfzc/stagesep2-sample.git && cd stagesep2-sample && python sample.py
